
definitions:
  steps:
    - step: &build
        image: node:18.5
        name: Build
        caches:
          - node
        script:
          - npm install
          - npm run build
        artifacts:
          - dist/**

    - step: &deploy
        name: Deploy
        clone:
          enabled: false
        script:
          - rsync -avh dist/ ${USERNAME}@${HOST}:/usr/share/${USERNAME}/${SERVICENAME}/ --delete-after

pipelines:
  branches:
    dev:
      - step: *build

      - step:
          <<: *deploy
          name: Deploy STAGING
          deployment: Staging

    master:
      - step: *build

#      - step:
#          <<: *deploy
#          name: Deploy STAGING
#          deployment: Staging

      - step:
          name: Deploy PRODUCTION
          image: atlassian/pipelines-awscli
          deployment: Production
#          trigger: manual
          clone:
            enabled: false
          script:
            - echo main
            - aws s3 sync ./dist s3://new-client.axpara.com --acl public-read --delete --cache-control max-age=0 --exclude "*" --include "index.html"
            - aws s3 sync ./dist s3://new-client.axpara.com --acl public-read --cache-control max-age=3600

      - step:
          name: Add build tag
          script:
            - git tag -am "Tagging for release ${BITBUCKET_BUILD_NUMBER}" release-${BITBUCKET_BUILD_NUMBER}
            - git push origin release-${BITBUCKET_BUILD_NUMBER}

